version: '3'
services:
  # Next.js application
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  # PostgreSQL database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: booking-db
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: uyg@xvp5WGD8wvd7pea
    ports:
      - "5432:5432"

  # Prisma migrations
  prisma-migrate:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://booking:uyg@xvp5WGD8wvd7pea@postgres:5432/booking-db
    command: ["npx", "prisma", "migrate", "dev"]

